import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { DATA_DIR } from '../config.js';

// Load WFCD community data files
const solNodes = JSON.parse(readFileSync(resolve(DATA_DIR, 'solNodes.json'), 'utf8'));
const languages = JSON.parse(readFileSync(resolve(DATA_DIR, 'languages.json'), 'utf8'));
const sortieData = JSON.parse(readFileSync(resolve(DATA_DIR, 'sortieData.json'), 'utf8'));

// Load item image lookup (generated by npm run update-data)
const itemImagesPath = resolve(DATA_DIR, 'itemImages.json');
const itemImages = existsSync(itemImagesPath)
  ? JSON.parse(readFileSync(itemImagesPath, 'utf8'))
  : {};

const IMAGE_CDN = 'https://cdn.warframestat.us/img';

// Build a case-insensitive item lookup from the languages file
const itemLookup = new Map();
for (const [key, val] of Object.entries(languages)) {
  itemLookup.set(key.toLowerCase(), val.value || val);
}

import { e, tierEmoji, factionEmoji } from './emojis.js';

export const VOID_TIERS = {
  VoidT1: { name: 'Lith', get emoji() { return tierEmoji('VoidT1'); } },
  VoidT2: { name: 'Meso', get emoji() { return tierEmoji('VoidT2'); } },
  VoidT3: { name: 'Neo', get emoji() { return tierEmoji('VoidT3'); } },
  VoidT4: { name: 'Axi', get emoji() { return tierEmoji('VoidT4'); } },
  VoidT5: { name: 'Requiem', get emoji() { return tierEmoji('VoidT5'); } },
  VoidT6: { name: 'Omnia', get emoji() { return tierEmoji('VoidT6'); } },
};

export const FACTIONS = {
  FC_GRINEER: { name: 'Grineer', get emoji() { return factionEmoji('FC_GRINEER'); } },
  FC_CORPUS: { name: 'Corpus', get emoji() { return factionEmoji('FC_CORPUS'); } },
  FC_INFESTATION: { name: 'Infested', get emoji() { return factionEmoji('FC_INFESTATION'); } },
  FC_OROKIN: { name: 'Corrupted', get emoji() { return factionEmoji('FC_OROKIN'); } },
  FC_SENTIENT: { name: 'Sentient', get emoji() { return factionEmoji('FC_SENTIENT'); } },
};

export function getNodeName(code) {
  const node = solNodes[code];
  if (node) return node.value;
  return code;
}

export function getNodeDetails(code) {
  return solNodes[code] || { value: code, enemy: 'Unknown', type: 'Unknown' };
}

export function getMissionType(code) {
  const missionMap = {
    MT_EXTERMINATION: 'Exterminate',
    MT_SURVIVAL: 'Survival',
    MT_DEFENSE: 'Defense',
    MT_MOBILE_DEFENSE: 'Mobile Defense',
    MT_RESCUE: 'Rescue',
    MT_SABOTAGE: 'Sabotage',
    MT_CAPTURE: 'Capture',
    MT_ASSASSINATION: 'Assassination',
    MT_SPY: 'Spy',
    MT_INTERCEPTION: 'Interception',
    MT_ARTIFACT: 'Disruption',
    MT_TERRITORY: 'Interception',
    MT_CORRUPTION: 'Void Flood',
    MT_ALCHEMY: 'Alchemy',
    MT_VOID_CASCADE: 'Void Cascade',
    MT_EXCAVATION: 'Excavation',
    MT_HIVE: 'Hive',
    MT_INTEL: 'Spy',
    MT_ASSAULT: 'Assault',
    MT_RAILJACK: 'Railjack',
    MT_SKIRMISH: 'Skirmish',
    MT_VOLATILE: 'Volatile',
    MT_ORPHIX: 'Orphix',
  };
  return missionMap[code] || code.replace('MT_', '').replace(/_/g, ' ');
}

export function getTier(modifier) {
  return VOID_TIERS[modifier] || { name: modifier, get emoji() { return e('unknown'); } };
}

export function getRegion(id) {
  const regions = {
    0: 'Earth', 1: 'Venus', 2: 'Mercury', 3: 'Mars',
    4: 'Phobos', 5: 'Void', 6: 'Jupiter', 7: 'Saturn',
    8: 'Uranus', 9: 'Neptune', 10: 'Pluto', 11: 'Sedna',
    12: 'Ceres', 13: 'Eris', 14: 'Europa', 15: 'Lua',
    16: 'Deimos', 17: 'Kuva Fortress', 18: 'Zariman',
    19: 'Void', 20: 'Veil Proxima', 21: 'Earth Proxima',
    22: 'Duviri',
  };
  return regions[id] || `Region ${id}`;
}

export function getBoss(code) {
  const boss = sortieData.bosses?.[code];
  if (boss) return boss.name;
  return code.replace('SORTIE_BOSS_', '').replace(/_/g, ' ');
}

export function getModifier(code) {
  return sortieData.modifierTypes?.[code] || code.replace('SORTIE_MODIFIER_', '').replace(/_/g, ' ');
}

export function getFaction(code) {
  return FACTIONS[code] || { name: code.replace('FC_', ''), get emoji() { return e('unknown'); } };
}

export function getChallengeName(path) {
  if (!path) return { title: 'Unknown', desc: '' };
  const lower = path.toLowerCase();
  if (itemLookup.has(lower)) {
    const val = languages[Object.keys(languages).find(k => k.toLowerCase() === lower)];
    if (val && typeof val === 'object') return { title: val.value || 'Unknown', desc: val.desc || '' };
    return { title: String(val), desc: '' };
  }
  const raw = path.split('/').pop()
    .replace(/^Season(Daily|Weekly|Elite)?/, '')
    .replace(/^Permanent/, '')
    .replace(/(\d+)$/, ' $1')
    .replace(/([A-Z])/g, ' $1')
    .replace(/\s+/g, ' ')
    .trim();
  return { title: raw, desc: '' };
}

export function getItemName(path) {
  if (!path) return 'Unknown';

  const lower = path.toLowerCase();
  if (itemLookup.has(lower)) return itemLookup.get(lower);

  const storeVariant = lower.replace('/lotus/types/', '/lotus/storeitems/types/');
  if (itemLookup.has(storeVariant)) return itemLookup.get(storeVariant);

  const noPrefix = '/lotus/storeitems/' + lower.split('/lotus/')[1];
  if (itemLookup.has(noPrefix)) return itemLookup.get(noPrefix);

  return path.split('/').pop().replace(/([A-Z])/g, ' $1').trim();
}

export function getItemImageUrl(path) {
  if (!path) return null;

  const lower = path.toLowerCase();

  if (itemImages[lower]) return `${IMAGE_CDN}/${itemImages[lower].img}`;

  const stripped = lower.replace('/lotus/storeitems/', '/lotus/');
  if (itemImages[stripped]) return `${IMAGE_CDN}/${itemImages[stripped].img}`;

  const withStore = lower.replace('/lotus/types/', '/lotus/storeitems/types/');
  if (itemImages[withStore]) return `${IMAGE_CDN}/${itemImages[withStore].img}`;

  return null;
}
